name: DockerTar

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3


    - name: Construir las imágenes Docker
      run: |
        docker build -t apache:latest -f apache .
        docker build -t ftp:latest -f ftp .
        docker build -t ssh:latest -f ssh .

    - name: Guardar las imágenes en un solo archivo tar
      run: |
        docker save -o envidia.tar apache:latest ftp:latest ssh:latest

    - name: Subir la imagen como artefacto
      uses: actions/upload-artifact@v4
      with:
        name: envidia
        path: envidia.tar